### ISSUE TITLE
About Flatlist

### ISSUE THREAD

**Issue by URvesh109** [spencercarli/react-native-flatlist-demo#2]
Your flatlist tutorial help me lot it was awesome.
I am having query regarding flatlist. If you will provide any suggestion I will be much obliged.

Query
I have Flatlist which has n-number of buttons, when a user click on any button then that specific button should change its styling.

**Comment by 7laria** [comment]
you need to create the button as separate component and then set different style based on selected props. for example:
`...
export default class MyButton extends Component{
render(){
<TouchableOpacity style={(this.props.selected)?style.setyleSelected:style.styleDeselected}/>
}
export const style=StyleSheet.create({
styleSelected:{ your style here},
styleDeselected:{ your style here}
})`
