### ISSUE TITLE
Hi spencercarli... How does the seed work in your api

### ISSUE THREAD

**Issue by ddnazzah** [spencercarli/react-native-flatlist-demo#3]

**Comment by spencercarli** [comment]
It just makes a remote request to the random user api. You can see that here https://github.com/spencercarli/react-native-flatlist-demo/blob/master/FlatListDemo.js#L23

**Comment by ddnazzah** [comment]
yea, i know the api  makes a remote  request but i I'm talking about the seed. Why do you increment the seed in the handleRefresh function. I want to understand how the seed works

**Comment by spencercarli** [comment]
It just gets a new set of data from the api so we can see that the data is being refreshed. here's the docs on it https://randomuser.me/documentation#seeds
