### ISSUE TITLE
Calls to handleLoadMore before even starting to scroll in the list

### ISSUE THREAD

**Issue by PtitNome** [spencercarli/react-native-flatlist-demo#5]
When I run the application, before doing any user input (scrolling the to bottom), there is many calls made to handleLoadMore() (onEndReached). The list is appending new data without need!

It looks like an infinite loop...

**Comment by PtitNome** [comment]
Actually, I resolved the issue by setting the onEdnReachedThreshold to {1} instead of 50. Some explanation about that would be appreciated!

**Comment by spencercarli** [comment]
I'm not sure why it would be called so much (that's a common issue). The reason it's stopping is because you're no longer in that threshold. Debounce the function might help - or putting some other kind of check in place to avoid the infinite loop
